### ISSUE TITLE
Login form does not work

### ISSUE THREAD

**Issue by Dibbya40** [zlfben/trace2tap#3]
Hello. When I submit the credentials in the login form and click the login button, it does not take me to the next page. It stays as it is. Could you please help me to solve this?
![Screenshot from 2020-10-15 21-21-55](https://user-images.githubusercontent.com/72954396/96202431-2c883100-0f2d-11eb-9985-2491e428159a.png)

**Comment by AlexDmr** [comment]
got the same problem :
core.js:15724 ERROR 
HttpErrorResponse
error: ProgressEvent
bubbles: false
cancelBubble: false
cancelable: false
composed: false
currentTarget: XMLHttpRequest {__zone_symbol__xhrSync: false, __zone_symbol__xhrURL: "http://localhost/backend/user/get_cookie/", __zone_symbol__loadfalse: Array(1), __zone_symbol__errorfalse: null, __zone_symbol__xhrScheduled: true, …}
defaultPrevented: false
eventPhase: 0
isTrusted: true
lengthComputable: false
loaded: 0
path: []
returnValue: true
srcElement: XMLHttpRequest {__zone_symbol__xhrSync: false, __zone_symbol__xhrURL: "http://localhost/backend/user/get_cookie/", __zone_symbol__loadfalse: Array(1), __zone_symbol__errorfalse: null, __zone_symbol__xhrScheduled: true, …}
target: XMLHttpRequest {__zone_symbol__xhrSync: false, __zone_symbol__xhrURL: "http://localhost/backend/user/get_cookie/", __zone_symbol__loadfalse: Array(1), __zone_symbol__errorfalse: null, __zone_symbol__xhrScheduled: true, …}
timeStamp: 5669.129999998404
total: 0
type: "error"
__proto__: ProgressEvent
headers: HttpHeaders {normalizedNames: Map(0), lazyUpdate: null, headers: Map(0)}
message: "Http failure response for http://localhost/backend/user/get_cookie/: 0 Unknown Error"
name: "HttpErrorResponse"
ok: false
status: 0
statusText: "Unknown Error"
url: "http://localhost/backend/user/get_cookie/"
__proto__: HttpResponseBase

**Comment by AlexDmr** [comment]
I guess the problem is that docker does not expose the correct ports, I had to change the docker compose config file so that 4200 port is mapped to a host port. Probably some other ports have to be exposed ?

**Comment by zlfben** [comment]
Dibbya's problem was solved by doing this:
```
adding "vine==1.3.0" as a line in 
trace2tap/iot-tap-backend/requirements.txt.
```

The issue was vine changed the API in the newest version which led to an import error in backend.

**Comment by Dibbya40** [comment]
Yes. My problem was solved. Thank you.

**Comment by AlexDmr** [comment]
Thanks for the information.
Actually the problem persists, here are some informations that I gathered :
docker ps
CONTAINER ID        IMAGE                COMMAND                  CREATED             STATUS              PORTS                    NAMES
7f86dba2bdb8        redis                "docker-entrypoint.s…"   2 minutes ago       Up 2 minutes        6379/tcp                 trace2tap_redis_1
724329fc67c7        trace2tap_frontend   "ng serve --host 0.0…"   2 minutes ago       Up 2 minutes        0.0.0.0:4200->4200/tcp   trace2tap_frontend_1
bf7664ef7ed1        trace2tap_postgres   "/usr/lib/postgresql…"   2 minutes ago       Up 2 minutes        5432/tcp                 trace2tap_postgres_1

__________
The logs of trace2tap_celery_beat_1 displays 
sh: 1: ../init-celery-beat.sh: not found

__________
as with trace2tap_iotcore_1 
sh: 1: ../init-core.sh: not found

_____
same kind of error with others containers

**Comment by zlfben** [comment]
Thanks for the information! It seems to be a separate issue. I created a new issue. Please refer to the new one.
